### ISSUE TITLE
后台设置个人信息提交时候出现的问题

### ISSUE THREAD

**Issue by pandaOreo** [quarkcms/quark-doc#1]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/35425100/156516630-660a6903-c853-418a-82d0-743aee8828f8.png">

<img width="575" alt="image" src="https://user-images.githubusercontent.com/35425100/156516667-35bfefac-ddd1-4dcc-8605-a0c9fd382b5e.png">

## 在提交的时候  sql把/api/admin/account/action/change-account也update了,显示没有这个字段

**Comment by tangtanglove** [comment]
刚才测试了一下，未发现此问题；麻烦把环境提供一下。

**Comment by pandaOreo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
