### ISSUE TITLE
学习 quarkgo 文档中遇到的问题

### ISSUE THREAD

**Issue by oknixus** [quarkcms/quark-doc#2]
1. 文档的示例代码中有 `adminresource`，但是在代码中却没有找到这个 package 的出处，导致代码无法运行
2. 在`main.go`中`AdminLayout`以及`&builder.AdminLayout{}`也是找不到的
目前遇到这两个问题，请问是少安装了依赖包吗？

**Comment by tangtanglove** [comment]
参考示例吧：https://github.com/quarkcloudio/quark-smart
