### ISSUE TITLE
希望改进的地方-图片

### ISSUE THREAD

**Issue by soul-key** [quarkcms/quark-doc#3]
1.图片上传路径如何指定？文档中没有找到相关信息。
2.图片字段最终的保存格式（JSON）一些没用的字段是否能删除掉

**Comment by tangtanglove** [comment]
![image](https://github.com/quarkcloudio/quark-doc/assets/60868863/201f566b-71f6-48dc-8081-1d9065ed8ff8)
参考这里

**Comment by tangtanglove** [comment]
图片字段没用的字段，可以根据自己的需求调整；但是在编辑页面，需要再次重组成类似的json数据才能展示
